Repository NREL-Sienna/InfrastructureSystems.jl, pull requests merged in 2020-09, with the labels that each got.

#120 Refactor serialization
  Project.toml
  docs/src/user_guide/guide.md
  src/InfrastructureSystems.jl
  src/component.jl
  src/components.jl
  src/descriptors/structs.json
  src/forecast_metadata.jl
  src/forecast_parser.jl
  src/forecasts.jl
  src/generated/DeterministicInternal.jl
  src/generated/PiecewiseFunctionInternal.jl
  src/generated/ProbabilisticInternal.jl
  src/generated/ScenarioBasedInternal.jl
  src/in_memory_time_series_storage.jl
  src/internal.jl
  src/serialization.jl
  src/system_data.jl
  src/time_series_storage.jl
  src/utils/generate_structs.jl
  src/utils/print.jl
  src/utils/recorder_events.jl
  src/utils/test.jl
  src/utils/utils.jl
  src/validation.jl
  test/Project.toml
  test/common.jl
  test/data/forecasts/ComponentsAsColumnsNoTime.json
  test/runtests.jl
  test/test_components.jl
  test/test_forecasts.jl
  test/test_internal.jl
  test/test_recorder.jl
  test/test_serialization.jl
  test/test_system_data.jl
  test/test_utils.jl
Labels: breaking, enhancement

#123 Rename forecasts to time series
  docs/src/user_guide/guide.md
  src/InfrastructureSystems.jl
  src/component.jl
  src/components.jl
  src/descriptors/structs.json
  src/forecast_metadata.jl
  src/forecast_parser.jl
  src/forecasts.jl
  src/generated/Deterministic.jl
  src/generated/DeterministicInternal.jl
  src/generated/DeterministicMetadata.jl
  src/generated/PiecewiseFunction.jl
  src/generated/PiecewiseFunctionInternal.jl
  src/generated/Probabilistic.jl
  src/generated/ProbabilisticInternal.jl
  src/generated/ProbabilisticMetadata.jl
  src/generated/ScenarioBased.jl
  src/generated/ScenarioBasedInternal.jl
  src/generated/Scenarios.jl
  src/generated/ScenariosMetadata.jl
  src/generated/includes.jl
  src/hdf5_time_series_storage.jl
  src/in_memory_time_series_storage.jl
  src/internal.jl
  src/serialization.jl
  src/supplemental_constructors.jl
  src/system_data.jl
  src/time_array_wrapper.jl
  src/time_series_container.jl
  src/time_series_data.jl
  src/time_series_formats.jl
  src/time_series_parameters.jl
  src/time_series_parser.jl
  src/utils/generate_structs.jl
  src/utils/print.jl
  src/utils/test.jl
  src/utils/utils.jl
  test/common.jl
  test/data/time_series/ComponentsAsColumnsNoTime.csv
  test/data/time_series/ComponentsAsColumnsNoTime.json
  test/data/time_series/DateTimeAsColumn.csv
  test/data/time_series/DateTimePeriodAsColumn.csv
  test/data/time_series/YMDPeriodAsColumn.csv
  test/data/time_series/YMDPeriodAsHeader.csv
  test/runtests.jl
  test/test_serialization.jl
  test/test_time_array_wrapper.jl
  test/test_time_series.jl
  test/test_time_series_formats.jl
  test/test_time_series_storage.jl
Labels: breaking

#124 use run instead of cp
  src/hdf5_time_series_storage.jl
  src/time_series_storage.jl
  src/utils/utils.jl
Labels: bug, enhancement

#125 Add Deterministic constructors to support all input formats
  src/supplemental_constructors.jl
  src/system_data.jl
  src/time_series_parser.jl
  test/test_time_series.jl
Labels: breaking

#126 time series split part 1
  .gitignore
  Project.toml
  src/InfrastructureSystems.jl
  src/abstract_time_series.jl
  src/component.jl
  src/components.jl
  src/descriptors/structs.json
  src/forecasts.jl
  src/generated/Deterministic.jl
  src/generated/DeterministicMetadata.jl
  src/generated/Probabilistic.jl
  src/generated/ProbabilisticMetadata.jl
  src/generated/Scenarios.jl
  src/generated/ScenariosMetadata.jl
  src/generated/SingleTimeSeries.jl
  src/generated/SingleTimeSeriesMetadata.jl
  src/generated/includes.jl
  src/hdf5_time_series_storage.jl
  src/in_memory_time_series_storage.jl
  src/single_time_series_data.jl
  src/static_time_series.jl
  src/supplemental_constructors.jl
  src/system_data.jl
  src/time_array_container.jl
  src/time_array_wrapper.jl
  src/time_series_container.jl
  src/time_series_parameters.jl
  src/time_series_parser.jl
  src/utils/print.jl
  test/Project.toml
  test/common.jl
  test/test_time_series.jl
  test/test_utils.jl
Labels: breaking
